android/src/main/java/com/apparence/camerawesome/image/ImgConverterThreaded.java

Fix crash in rebuild widget with imagesStreamBuilder
- ( ) 🛠 My feature contain breaking change.

fix init stream after relaunch camera

---

CHANGELOG.md
android/src/main/java/com/apparence/camerawesome/CameraPreview.java
android/src/main/java/com/apparence/camerawesome/CameraStateManager.java

unlock focus now restart session correctly after taking a photo

 - unlock focus now restart session correctly after taking a photo

---

example/test_driver/app.dart
ios/Classes/CameraPreview/CameraView.m

Fix an issue which can crash the app when switching audio on iOS in video capture mode.

🚑 Fix enable audio switch issue

---

README.md
example/ios/Flutter/.last_build_id
example/ios/RunnerTests/RunnerTests.m
example/pubspec.lock
example/pubspec.yaml
ios/Classes/CameraPreview/CameraView.m
lib/camerapreview.dart

🐛 [iOS] Fix some issues on iOS #55

---

CHANGELOG.md
README.md
example/pubspec.lock
lib/camerapreview.dart
pubspec.yaml

Build won't be run without fully init

- prevent build without fully init

---

android/src/main/java/com/apparence/camerawesome/CameraPreview.java

Fix take picture on some android devices that stays locked without active focus
from : https://github.com/Apparence-io/camera_awesome/pull/83
- [ x ] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [ x ] 🤝 I match the actual coding style.

from Andrew pr / split android fix

---

example/pubspec.lock
example/pubspec.yaml
lib/camerapreview.dart
pubspec.lock
pubspec.yaml

reasons:
- on android onPermissionsResult null check was requiring onPermissionsResult to be provided
solutions:
- changed it to optional by wrapping with another null check like in lines 194 - 196
references #76
Adds another null check to make onPermissionsResult optional. Also updated dependencies.

fix for null safety issue onPermissionsResult :bug:

---

README.md
example/ios/Podfile.lock
example/lib/main.dart
example/lib/main_hero.dart
example/pubspec.lock
example/pubspec.yaml
lib/camerapreview.dart
pubspec.lock

Fix an issue when trying to set initialize orientation.
Close #100
Remove orientation parameters

🐛 Fix landscape orientation video preview

---

.github/PULL_REQUEST_TEMPLATE.md
example/lib/main.dart
example/pubspec.lock
ios/Classes/CameraPreview/CameraPreview.m
ios/Classes/Controllers/Picture/CameraPictureController.m
lib/camerapreview.dart
lib/camerawesome_plugin.dart
pubspec.yaml

This PR fix an issue when setting front sensor by default on iOS.
Fix #104 #62 #123 

🐛 Fix iOS front sensor orientation

---

android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraAwesomeX.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/ExifPreferences.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/Pigeon.kt
lib/camerawesome_plugin.dart
lib/pigeon.dart
lib/src/builder/camera_awesome_builder.dart
lib/src/layouts/awesome/awesome_layout.dart
lib/src/layouts/awesome/widgets/aspect_ratio.dart
lib/src/layouts/awesome/widgets/awesome_location_button.dart
lib/src/layouts/awesome/widgets/media_preview.dart
lib/src/logger.dart
lib/src/orchestrator/analysis/analysis_controller.dart
lib/src/orchestrator/camera_context.dart
lib/src/orchestrator/models/exif_preferences_data.dart
lib/src/orchestrator/sensor_config.dart
lib/src/orchestrator/states/picture_state.dart
lib/src/orchestrator/states/preparing_state.dart
lib/src/orchestrator/states/state_definition.dart
lib/src/orchestrator/states/video_recording_state.dart
lib/src/orchestrator/states/video_state.dart
pigeons/interface.dart

Users can now save GPS location when taking pictures
Note: I also started implementing a basic Logger for CamerAwesome which will be disabled by default (instead of printing everything, clients might not be interested).

Plug back ExifPreferences to new architecture

---

README.md
docs/appendix/roadmap.mdx
docs/getting_started/awesome-ui.mdx
docs/getting_started/custom-ui.mdx
lib/src/builder/camera_awesome_builder.dart
lib/src/layouts/awesome/widgets/awesome_camera_preview.dart

- Adding a cover mode that cover all area. 
- Moving current cover mode to contain mode

preview : Cover / Contain

---

lib/src/orchestrator/states/preparing_camera_state.dart

Fixes the ImageAnalysisController not started as reported in #167 

Fix imageAnalysisController not started

---

README.md
android/build.gradle
android/src/main/kotlin/com/apparence/camerawesome/cameraX/AutoFitPreviewBuilder.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraAwesomeX.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraXState.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/Pigeon.kt
docs/appendix/roadmap.mdx
docs/getting_started/awesome-ui.mdx
docs/getting_started/custom-ui.mdx
docs/widgets/awesome_buttons.mdx
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/integration_test/ui_test.dart
example/lib/ai_analysis_faces.dart
example/lib/custom_ui_example_1.dart
example/lib/main.dart
lib/camerawesome_plugin.dart
lib/pigeon.dart
lib/src/builder/camera_awesome_builder.dart
lib/src/layouts/awesome/widgets/awesome_camera_gesture_detector.dart
lib/src/layouts/awesome/widgets/awesome_camera_preview.dart
lib/src/orchestrator/camera_context.dart
lib/src/orchestrator/models/save_config.dart
lib/src/orchestrator/states/preparing_camera_state.dart
pigeons/interface.dart

- Add initial parameters (aspect ratio) and use them
- Add Aspect Ratio 1:1 on Android
- Updated doc
I renamed SaveConfig.photoAndVideo() params to use "photo" instead of "image" for better consistency.

Improve initial params, add aspect ratio 1:1

---

README.md
docs/index.mdx
ios/Classes/CameraPreview/CameraPreview.h
ios/Classes/CameraPreview/CameraPreview.m
ios/Classes/CamerawesomePlugin.m
ios/Classes/Constants/CameraSensorType.h
lib/camerawesome_plugin.dart
lib/src/layouts/awesome/awesome_camera_layout.dart
lib/src/layouts/awesome/widgets/awesome_camera_preview.dart
lib/src/layouts/awesome/widgets/awesome_sensor_type_selector.dart
lib/src/orchestrator/camera_context.dart
lib/src/orchestrator/models/sensor_config.dart
lib/src/orchestrator/models/sensor_type.dart
lib/src/orchestrator/states/camera_state.dart

Add the ability to switch between **telephoto**, **wide angle**, **ultra wide angle** & **true depth** camera sensors.
This partially add feature requested in
#140
#35

✨ Add dynamic sensor switching for iOS

---

example/integration_test/ui_test.dart
example/lib/custom_ui_example_2.dart
lib/src/layouts/awesome/widgets/awesome_location_button.dart
lib/src/orchestrator/models/sensor_type.dart
pubspec.yaml

Format files to get 130/130 with ```pana```

🚨 Format files

---

README.md
docs/getting_started/awesome-ui.mdx
docs/getting_started/custom-ui.mdx
docs/getting_started/installing.mdx
docs/widgets/awesome_buttons.mdx
docs/widgets/awesome_camera_mode_selector.mdx
example/integration_test/video_test.dart
example/lib/ai_analysis_barcode.dart
example/lib/custom_ui_example_1.dart
example/lib/custom_ui_example_2.dart
example/lib/custom_ui_example_3.dart
lib/src/builder/camera_awesome_builder.dart
lib/src/layouts/awesome/awesome_camera_layout.dart
lib/src/layouts/awesome/widgets/awesome_camera_preview.dart
lib/src/layouts/awesome/widgets/widgets.dart

- Add `previewSize` and `previewRect` to CameraLayoutBuilder
Constructors should be updated to add the new arguments.

Update CamerAwesomeBuilder constructors

---

docs/appendix/roadmap.mdx

📝 Improve roadmap

---

lib/src/layouts/awesome/widgets/awesome_sensor_type_selector.dart

Replace "0,5x" to "0.5x"
- Fix #199 

🐛 Fix ultra wide angle typo

---

ios/Classes/CameraPreview/CameraPreview.m
ios/Classes/CamerawesomePlugin.m

Add a guard to prevent recording video on streaming mode.
Fix #202 

🚑 Fix iOS image stream guard

---

CHANGELOG.md
example/lib/main.dart
lib/src/layouts/awesome/widgets/awesome_camera_preview.dart

This should fix the wrong aspect ratio of the preview on iOS.
See #216.

🐛 Fix preview crop

---

ios/Classes/Controllers/Picture/CameraPictureController.h
ios/Classes/Controllers/Picture/CameraPictureController.m

Fix aspect ratio crop on iOS.
🚨 Currently Portrait 4:3 crop not working...
Fix #224 

🚧 🐛 Fix crop aspect ratio for iOS

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraPermissions.kt
docs/getting_started/installing.mdx
example/pubspec.lock
pubspec.lock
pubspec.yaml

Plugins might have compatibility problems with play-services-location version.
We used v21 but it includes a breaking change and can't work with v20.
This change let users define which version they want to use in gradle.

🔧 Expose play services location version

---

.vscode/launch.json
example/ios/Podfile.lock
example/lib/subroute_camera.dart
ios/Classes/CamerawesomePlugin.m

🐛 release the texture before closing camera

---

example/ios/Podfile.lock
ios/Classes/CamerawesomePlugin.m
ios/Classes/Controllers/Permissions/PermissionsController.h
ios/Classes/Controllers/Permissions/PermissionsController.m

Microphone permission is now prompted when video mode is active.
Close #247

🚑️ Fix iOS microphone permission

---

lib/src/layouts/awesome/widgets/widgets.dart

Export AwesomeCircleIconButton widget 
Close #254 

🚚 export awesome circle icon button

---

ios/Classes/CameraPreview/CameraPreview.m
ios/Classes/Controllers/Picture/CameraPictureController.m
ios/Classes/Controllers/Video/VideoController.h
ios/Classes/Controllers/Video/VideoController.m

Video recorded on landscape mode are now written in the correct orientation.
Close #259

🐛 Fix video file in landscape

---

lib/src/widgets/preview/awesome_camera_preview.dart

This PR should fix aspect ratio changes animation.

🐛 Fix aspect ratio anim

---

android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraAwesomeX.kt

[Android] 🐛 Don't rebind to lifecycle if just changing flash

---

README.md
android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraAwesomeX.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraXState.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/Pigeon.kt
docs/getting_started/awesome-ui.mdx
docs/getting_started/custom-ui.mdx
example/android/build.gradle
example/ios/Runner.xcodeproj/project.pbxproj
ios/Classes/CameraPreview/CameraPreview.h
ios/Classes/CameraPreview/CameraPreview.m
ios/Classes/CamerawesomePlugin.m
ios/Classes/Controllers/Picture/CameraPictureController.h
ios/Classes/Controllers/Picture/CameraPictureController.m
ios/Classes/Pigeon/Pigeon.h
ios/Classes/Pigeon/Pigeon.m
lib/camerawesome_plugin.dart
lib/pigeon.dart
lib/src/orchestrator/models/sensor_config.dart
lib/src/widgets/camera_awesome_builder.dart
pigeons/interface.dart

This PR introduce front camera mirroring option to mirror or not the front camera.
This is the **Dart** 💙 & **iOS** 🍏 implementation.
Android part need to be done.
Partially close #255 

✨🍏 Add front camera mirroring option

---

ios/Classes/Controllers/Picture/CameraPictureController.m

This PR intent to fix all aspect ratio issues on iOS & iPadOS.
Portrait & Landscape aspect ratio crop will work normally.
Close #226

🐛 Fix aspect ratio on iOS

---

.idea/camera_awesome.iml
CHANGELOG.md
README.md
docs/getting_started/installing.mdx
pubspec.yaml

Preparation for the release of version 1.3.0.

📝 Write changelog for 1.3.0

---

ios/Classes/CameraPreview/CameraPreview.h
ios/Classes/CameraPreview/CameraPreview.m
ios/Classes/CamerawesomePlugin.m

This **PR** fix the initial aspect ratio on iOS / iPadOS.

🐛 Initial aspect ratio initialization on iOS / iPadOS

---

CHANGELOG.md
lib/pigeon.dart
lib/src/orchestrator/models/sensor_config.dart
lib/src/widgets/preview/awesome_camera_preview.dart

- Lint & format code before 1.3.0 release.
- Update Changelog.

🚨 Format & lint code before 1.3.0 release

---

CHANGELOG.md
README.md
pubspec.yaml

📝 Update changelog for v1.3.1

---

lib/camerawesome_plugin.dart
lib/src/orchestrator/models/sensor_config.dart

This PR intend to remove unused method luminosity level which was not implemented on iOS & Android.

🗑️ Remove luminosity level stream

---

example/pubspec.lock
lib/camerawesome_plugin.dart
lib/pigeon.dart
lib/src/orchestrator/models/analysis/analysis_image.dart
lib/src/widgets/camera_awesome_builder.dart
pigeons/interface.dart
pubspec.yaml

🚨 Lint code

---

lib/src/widgets/layout/awesome_bottom_actions.dart

Fix use of capture button param in awesome bottom actions

🐛 Fix use of capture button param in awesome bottom actions

---

README.md
README.zh.md

- Add a Chinese README.zh.md file for the community

docs: add README.zh.md

---

docs/getting_started/custom-ui.mdx

Fix a copy paste error in the docs and apply the correct commands for sensorConfig (Brightness)
Docs contained a copy & paste error and did not specify the correct commands to listen and control the brightness of sensorConfig.
- [ X] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [ X] 🤝 I match the actual coding style.
- [X ] ✅ I ran ```flutter analyze``` without any issues.

FIX: Docs Brightness commands

---

android/src/main/kotlin/com/apparence/camerawesome/cameraX/Pigeon.kt
docs/image_analysis/image_analysis_configuration.mdx
ios/Classes/CameraPreview/SingleCameraPreview/SingleCameraPreview.m
ios/Classes/CamerawesomePlugin.m
ios/Classes/Constants/CaptureModes.h
ios/Classes/Pigeon/Pigeon.h
ios/Classes/Pigeon/Pigeon.m
ios/Classes/Utils/CaptureMode/CaptureModeUtils.h
ios/Classes/Utils/CaptureMode/CaptureModeUtils.m
lib/camerawesome_plugin.dart
lib/pigeon.dart
lib/src/orchestrator/states/preparing_camera_state.dart
pigeons/interface.dart

This feature fix microphone permission on iOS.
Close #335 

🐛 Fix microphone permission on iOS

---

docs/getting_started/multicam.mdx

📝 Fix multicam doc

---

CHANGELOG.md

The link to the migration guide in the Changelog was wrong. #176 

Update CHANGELOG.md migration link

---

example/lib/custom_ui_example_2.dart
example/pubspec.lock
lib/src/orchestrator/states/photo_camera_state.dart
lib/src/orchestrator/states/preparing_camera_state.dart
lib/src/widgets/buttons/awesome_capture_button.dart
lib/src/widgets/layout/awesome_bottom_actions.dart
pubspec.lock

This PR adds a function parameter "onCapture" to allow the user to perform an action immediately after taking a photo. It also allows the user customise the capture button
- [ x] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [x ] 🤝 I match the actual coding style.
- [x ] ✅ I ran ```flutter analyze``` without any issues.

Added onCapture function parameter, and customisable capture button

---

android/build.gradle
example/android/app/build.gradle
example/lib/custom_theme.dart
example/lib/custom_ui_example_3.dart
example/lib/main.dart
example/lib/multi_camera.dart
example/lib/preview_overlay_example.dart
example/lib/subroute_camera.dart
example/lib/utils/file_utils.dart
example/pubspec.lock
example/pubspec.yaml
pubspec.yaml

Upgrade camera x

---

android/src/main/AndroidManifest.xml

Resolves https://github.com/Apparence-io/CamerAwesome/issues/414

Remove package name from AndroidManifest.xml

---

example/ios/Runner/AppDelegate.swift
example/pubspec.lock
lib/src/orchestrator/states/preparing_camera_state.dart
lib/src/photofilters/filters/color_filters.dart
lib/src/photofilters/filters/image_filters.dart
lib/src/widgets/filters/awesome_filter_name_indicator.dart
lib/src/widgets/filters/awesome_filter_selector.dart
lib/src/widgets/utils/awesome_bouncing_widget.dart
pubspec.lock
pubspec.yaml

Update from #502 with `carousel_slider:5.0.0`

Update with carousel_slider:5.0.0

---

example/ios/Runner/AppDelegate.swift
example/pubspec.lock
lib/src/orchestrator/states/preparing_camera_state.dart
lib/src/photofilters/filters/color_filters.dart
lib/src/photofilters/filters/image_filters.dart
lib/src/widgets/filters/awesome_filter_name_indicator.dart
lib/src/widgets/filters/awesome_filter_selector.dart
lib/src/widgets/utils/awesome_bouncing_widget.dart
pubspec.lock
pubspec.yaml

Update dependencies:
-Pigeon
-Flutter sdk
-Carrousel_slider
-RxDart
- [X ] 📕 I read the [Contributing page](https://github.com/Apparence-io/camera_awesome/blob/master/CONTRIBUTING.md).
- [X ] 🛠 My feature contain breaking change.
Carrousel_slider is not supported and with last version of flutter 3.24 the library crash, because carrousel_slider name have conflict with material.

Update dependencies 

---

.gitignore
android/gradle/wrapper/gradle-wrapper.properties
android/src/main/kotlin/com/apparence/camerawesome/cameraX/AnalysisImageConverter.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraAwesomeX.kt
android/src/main/kotlin/com/apparence/camerawesome/cameraX/ImageAnalysisBuilder.kt
example/.gitignore
example/lib/utils/file_utils.dart
example/pubspec.lock
example/pubspec.yaml
lib/src/orchestrator/models/analysis/analysis_config.dart
lib/src/orchestrator/models/analysis/input_analysis.dart
pubspec.yaml

Credit from #553 
This adds support for RGBA_8888 format as CameraX supports this. Ref https://github.com/Apparence-io/CamerAwesome/issues/550 by @vongohren

Bkey inc/master

---

android/build.gradle
android/src/main/kotlin/com/apparence/camerawesome/cameraX/CameraXState.kt

Fix android crash when using another package with a newer camerax dependency

---

ios/camerawesome/Sources/camerawesome/CameraPreview/SingleCameraPreview/SingleCameraPreview.m

Fix(ios) setRecordingAudioMode not competed

---

ios/camerawesome/Sources/camerawesome/CameraPreview/SingleCameraPreview/SingleCameraPreview.m
ios/camerawesome/Sources/camerawesome/Controllers/Video/VideoController.m

Support orientation same android when device lock orientation

Fix(ios) orientation when device lock orientation

---

ios/camerawesome/Sources/camerawesome/Controllers/Analysis/AnalysisController.m

🖌️ Swap red and blue channels in .jpeg method of BGRA8888 function
